language: python

# using container based testing is faster, but you can't use sudo
sudo: false

python:
    - "3.6"

# command to install dependencies that require sudo
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
# addons:
#     apt:
#         packages:
#             - pyserial
#             - nose

# install other libraries using pip
install:
    - pip install -U pip setuptools
    - pip install .

# command to run tests
script: python -m nose -v -w tests test.py
